# Generated by Django 5.0.4 on 2024-05-17 17:35

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('insta_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
