# Generated by Django 5.0.4 on 2024-05-20 21:30

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionimage',
            name='promotion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='promo.promotion'),
        ),
        migrations.CreateModel(
            name='PromotionBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path)),
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='promo.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
