# Generated by Django 5.0.4 on 2024-05-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_alter_promotionimage_promotion_promotionbannerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionbannerimage',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo.promotion'),
        ),
        migrations.AlterField(
            model_name='promotionimage',
            name='promotion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo.promotion'),
        ),
    ]
