# Generated by Django 5.0.4 on 2024-05-21 19:24

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('부스', '부스'), ('푸드트럭', '푸드트럭'), ('플리마켓', '플리마켓')], max_length=10)),
                ('operator', models.CharField(max_length=10)),
                ('location', models.CharField(choices=[('사회과학관', '사회과학관'), ('혜화관', '혜화관'), ('팔정도', '팔정도'), ('원흥관', '원흥관'), ('만해광장', '만해광장'), ('학생회관', '학생회관'), ('학림관', '학림관')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longtude', models.FloatField()),
                ('insta_url', models.URLField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoothImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.image_upload_path)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boothimages', to='booth.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoothLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, editable=False, max_length=10)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='booth.booth')),
            ],
        ),
    ]
