# Generated by Django 5.0.4 on 2024-05-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
    ]
