# Generated by Django 5.0.4 on 2024-05-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0004_remove_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booth',
            name='location',
        ),
        migrations.RemoveField(
            model_name='booth',
            name='longitude',
        ),
        migrations.CreateModel(
            name='BoothLocationOperationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('사회과학관', '사회과학관'), ('혜화관', '혜화관'), ('팔정도', '팔정도'), ('원흥관', '원흥관'), ('만해광장', '만해광장'), ('학생회관', '학생회관'), ('학림관', '학림관')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_operation_times', to='booth.booth')),
            ],
            options={
                'unique_together': {('booth', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='BoothOperationTime',
        ),
    ]
