# Generated by Django 5.0.4 on 2024-05-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_remove_booth_latitude_remove_booth_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boothlocationoperationtime',
            unique_together=set(),
        ),
    ]
