# Generated by Django 5.0.4 on 2024-05-26 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_remove_booth_latitude_remove_booth_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Password must be a 4-digit number', regex='^\\d{4}$')]),
        ),
    ]
