# Generated by Django 5.0.4 on 2024-05-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_alter_boothlocationoperationtime_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boothlocationoperationtime',
            unique_together={('booth', 'date')},
        ),
    ]
