# Generated by Django 5.0.4 on 2024-05-27 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_alter_boothlocationoperationtime_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Error : Password must be a 4-digit number', regex='^\\d{4}$')]),
        ),
    ]
