# Generated by Django 5.0.4 on 2024-05-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0009_boothlike_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boothlike',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
