# Generated by Django 5.0.4 on 2024-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0010_alter_boothlike_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boothlike',
            name='fingerprint',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
